<script>
    import Banner from "./components/Banner.svelte";
    import Partners from "./components/Partners.svelte";

    const regionOptions = [
        { 
            key: 0,
            name: "All Regions",
            value: "all",
        },
        {
            key: 1,
            name: "APAC",
            value: "apac",
        },
        {
            key: 2,
            name: "EMEA",
            value: "emea",
        },
        {
            key: 3,
            name: "Latin America",
            value: "latin-america",
        },
        {
            key: 4,
            name: "North America",
            value: "north-america",
        },
        {
            key: 5,
            name: "Rest of World",
            value: "rest-of-world",
        },
        {
            key: 6,
            name: "Worldwide",
            value: "worldwide",
        }

    ];

const countryOptions = [

    { key: 0, name: "All Countries", value: "all" },
    { key: 1, name: "Albania", value: "albania" },
    { key: 2, name: "Argentina", value: "argentina" },
    { key: 3, name: "Armenia", value: "armenia" },
    { key: 4, name: "Australia", value: "australia" },
    { key: 5, name: "Austria", value: "austria" },
    { key: 6, name: "Azerbaijan", value: "azerbaijan" },
    { key: 7, name: "Bahrain", value: "bahrain" },
    { key: 8, name: "Bangladesh", value: "bangladesh" },
    { key: 9, name: "Barbados", value: "barbados" },
    { key: 10, name: "Belgium", value: "belgium" },
    { key: 11, name: "Bermuda", value: "bermuda" },
    { key: 12, name: "Bolivia, Plurinational State of", value: "bolivia-plurinational-state-of" },
    { key: 13, name: "Bosnia and Herzegovina", value: "bosnia-and-herzegovina" },
    { key: 14, name: "Brazil", value: "brazil" },
    { key: 15, name: "Bulgaria", value: "bulgaria" },
    { key: 16, name: "Cambodia", value: "cambodia" },
    { key: 17, name: "Canada", value: "canada" },
    { key: 18, name: "Cayman Islands", value: "cayman-islands" },
    { key: 19, name: "Chile", value: "chile" },
    { key: 20, name: "China", value: "china" },
    { key: 21, name: "Colombia", value: "colombia" },
    { key: 22, name: "Costa Rica", value: "costa-rica" },
    { key: 23, name: "Cote d'Ivoire", value: "cote-d-ivoire" },
    { key: 24, name: "Croatia", value: "croatia" },
    { key: 25, name: "Cyprus", value: "cyprus" },
    { key: 26, name: "Czech Republic", value: "czech-republic" },
    { key: 27, name: "Denmark", value: "denmark" },
    { key: 28, name: "Dominican Republic", value: "dominican-republic" },
    { key: 29, name: "Ecuador", value: "ecuador" },
    { key: 30, name: "Egypt", value: "egypt" },
    { key: 31, name: "Estonia", value: "estonia" },
    { key: 32, name: "Fiji", value: "fiji" },
    { key: 33, name: "Finland", value: "finland" },
    { key: 34, name: "France", value: "france" },
    { key: 35, name: "Gambia", value: "gambia" },
    { key: 36, name: "Georgia", value: "georgia" },
    { key: 37, name: "Germany", value: "germany" },
    { key: 38, name: "Greece", value: "greece" },
    { key: 39, name: "Guatemala", value: "guatemala" },
    { key: 40, name: "Hong Kong", value: "hong-kong" },
    { key: 41, name: "Hungary", value: "hungary" },
    { key: 42, name: "Iceland", value: "iceland" },
    { key: 43, name: "India", value: "india" },
    { key: 44, name: "Indonesia", value: "indonesia" },
    { key: 45, name: "Iraq", value: "iraq" },
    { key: 46, name: "Ireland", value: "ireland" },
    { key: 47, name: "Israel", value: "israel" },
    { key: 48, name: "Italy", value: "italy" },
    { key: 49, name: "Japan", value: "japan" },
    { key: 50, name: "Jordan", value: "jordan" },
    { key: 51, name: "Kazakhstan", value: "kazakhstan" },
    { key: 52, name: "Kenya", value: "kenya" },
    { key: 53, name: "Korea, Republic of", value: "korea-republic-of" },
    { key: 54, name: "Kosovo", value: "kosovo" },
    { key: 55, name: "Kuwait", value: "kuwait" },
    { key: 56, name: "Kyrgyzstan", value: "kyrgyzstan" },
    { key: 57, name: "Latvia", value: "latvia" },
    { key: 58, name: "Lebanon", value: "lebanon" },
    { key: 59, name: "Lithuania", value: "lithuania" },
    { key: 60, name: "Luxembourg", value: "luxembourg" },
    { key: 61, name: "Macedonia, the former Yugoslav Republic of", value: "macedonia-the-former-yugoslav-republic-of" },
    { key: 62, name: "Malaysia", value: "malaysia" },
    { key: 63, name: "Malta", value: "malta" },
    { key: 64, name: "Mauritius", value: "mauritius" },
    { key: 65, name: "Mexico", value: "mexico" },
    { key: 66, name: "Moldova, Republic of", value: "moldova-republic-of" },
    { key: 67, name: "Monaco", value: "monaco" },
    { key: 68, name: "Mongolia", value: "mongolia" },
    { key: 69, name: "Morocco", value: "morocco" },
    { key: 70, name: "Myanmar", value: "myanmar" },
    { key: 71, name: "Namibia", value: "namibia" },
    { key: 72, name: "Nepal", value: "nepal" },
    { key: 73, name: "Netherlands", value: "netherlands" },
    { key: 74, name: "New Caledonia", value: "new-caledonia" },
    { key: 75, name: "New Zealand", value: "new-zealand" },
    { key: 76, name: "Nigeria", value: "nigeria" },
    { key: 77, name: "Norway", value: "norway" },
    { key: 78, name: "Oman", value: "oman" },
    { key: 79, name: "Pakistan", value: "pakistan" },
    { key: 80, name: "Panama", value: "panama" },
    { key: 81, name: "Peru", value: "peru" },
    { key: 82, name: "Philippines", value: "philippines" },
    { key: 83, name: "Poland", value: "poland" },
    { key: 84, name: "Portugal", value: "portugal" },
    { key: 85, name: "Qatar", value: "qatar" },
    { key: 86, name: "Romania", value: "romania" },
    { key: 87, name: "Saudi Arabia", value: "saudi-arabia" },
    { key: 88, name: "Senegal", value: "senegal" },
    { key: 89, name: "Serbia", value: "serbia" },
    { key: 90, name: "Singapore", value: "singapore" },
    { key: 91, name: "Slovakia", value: "slovakia" },
    { key: 92, name: "Slovenia", value: "slovenia" },
    { key: 93, name: "South Africa", value: "south-africa" },
    { key: 94, name: "Spain", value: "spain" },
    { key: 95, name: "Sri Lanka", value: "sri-lanka" },
    { key: 96, name: "Sweden", value: "sweden" },
    { key: 97, name: "Switzerland", value: "switzerland" },
    { key: 98, name: "Taiwan", value: "taiwan" },
    { key: 99, name: "Thailand", value: "thailand" },
    { key: 100, name: "Togo", value: "togo" },
    { key: 101, name: "Trinidad and Tobago", value: "trinidad-and-tobago" },
    { key: 102, name: "Tunisia", value: "tunisia" },
    { key: 103, name: "Turkey", value: "turkey" },
    { key: 104, name: "Ukraine", value: "ukraine" },
    { key: 105, name: "United Arab Emirates", value: "united-arab-emirates" },
    { key: 106, name: "United Kingdom", value: "united-kingdom" },
    { key: 107, name: "United States", value: "united-states" },
    { key: 108, name: "Uruguay", value: "uruguay" },
    { key: 109, name: "Uzbekistan", value: "uzbekistan" },
    { key: 110, name: "Vietnam", value: "vietnam" }
];

const partnerTypes = [
        {
            value: "isMsp",
            title: "Managed security service provider",
            abbr: "MSP/MSSP",
        },
         {
            value: "isVar",
            title: "Value-Added Reseller (VAR)",
            abbr:  "Value-Added Reseller (VAR)"
        },
        {
            value: "isVad",
            title: "Value-Added Distributor (VAD)",
            abbr:  "Value-Added Distributor (VAD)"
        },
];

</script>

<Banner regionOptions={regionOptions} countryOptions={countryOptions} partnerTypes={partnerTypes}/>
<Partners />

